cuda_id: '5'
seed: 2022

log:
  path: "/home/chenzhongming/TVCG_wsi/logs"
  name: "hubmap_segmentation"

model:
  swin:
    embed_dim: 96
    depths:
      - 2
      - 2
      - 6
      - 2
    num_heads: 
      - 3
      - 6
      - 12
      - 24
    window_size: 7
    mlp_ratio: 4.
    qkv_bias: True
    qk_scale: null
    drop_rate: 0.
    attn_drop_rate: 0.
    drop_path_rate: 0.3
    ape: False
    patch_norm: True
    out_indices: 
      - 0
      - 1
      - 2
      - 3
    use_checkpoint: False
  swin_tiny_patch4_window7_224:
    checkpoint: '/data/chenzhongming/hubmap/hubmap256/pretrain_param/swin_tiny_patch4_window7_224_22k.pth'
    swin:
      embed_dim: 96
      depths: 
        - 2
        - 2
        - 6
        - 2
      num_heads: 
        - 3
        - 6
        - 12
        - 24
      window_size: 7
      ape: False
      drop_path_rate: 0.3
      patch_norm: True
      use_checkpoint: False
    upernet:
      in_channels:
        - 96
        - 192
        - 284
        - 768


dataset:
  batch_size: 4
  image_size: 768
  train: '/data/chenzhongming/hubmap/hubmap256/train/'
  masks: '/data/chenzhongming/hubmap/hubmap256/masks/'
  labels: '/data/chenzhongming/hubmap/hubmap256/train.csv'